package dev.dbexplorer.data.drivers.postgres

import dev.dbexplorer.data.drivers.DbSession
import dev.dbexplorer.domain.model.ConnectionProfile
import dev.dbexplorer.domain.model.DbException
import dev.dbexplorer.domain.model.DbKind
import dev.dbexplorer.domain.model.ReferentialAction
import dev.dbexplorer.domain.model.ResultChunk
import dev.dbexplorer.domain.model.SchemaRef
import dev.dbexplorer.domain.model.Secrets
import dev.dbexplorer.domain.model.SslMode
import dev.dbexplorer.domain.model.TableType
import kotlinx.coroutines.async
import kotlinx.coroutines.delay
import kotlinx.coroutines.flow.toList
import kotlinx.coroutines.runBlocking
import org.junit.After
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertTrue
import org.junit.Assume.assumeTrue
import org.junit.Before
import org.junit.Test

/**
 * Runs against a real server when DBX_PG_HOST is set, e.g.
 * `DBX_PG_HOST=localhost DBX_PG_PORT=5432 DBX_PG_USER=postgres ./gradlew :core:test`.
 */
class PostgresSessionIT {
    private lateinit var session: DbSession
    private val schema = "dbx_it_" + System.nanoTime()

    private fun profile(readOnly: Boolean = false) = ConnectionProfile(
        id = 7,
        name = "it",
        kind = DbKind.POSTGRES,
        host = System.getenv("DBX_PG_HOST").orEmpty(),
        port = System.getenv("DBX_PG_PORT")?.toInt(),
        database = System.getenv("DBX_PG_DB") ?: "postgres",
        username = System.getenv("DBX_PG_USER") ?: "postgres",
        sslMode = SslMode.DISABLE,
        readOnly = readOnly,
    )

    private val secrets get() = Secrets(System.getenv("DBX_PG_PASSWORD"))

    private suspend fun run(sql: String) = session.execute(sql).toList()

    @Before
    fun setUp() = runBlocking {
        assumeTrue("DBX_PG_HOST not set", !System.getenv("DBX_PG_HOST").isNullOrEmpty())
        session = PostgresDriver().connect(profile(), secrets)
        run("CREATE SCHEMA $schema")
        run(
            """
            CREATE TABLE $schema.author (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name varchar(100) NOT NULL,
                bio text DEFAULT 'n/a'
            )
            """.trimIndent(),
        )
        run(
            """
            CREATE TABLE $schema."Book" (
                isbn text, edition int, author_id bigint REFERENCES $schema.author ON DELETE CASCADE,
                price numeric(8, 2) CHECK (price >= 0), PRIMARY KEY (isbn, edition)
            )
            """.trimIndent(),
        )
        run("CREATE INDEX book_price_idx ON $schema.\"Book\" (price DESC)")
        run("COMMENT ON TABLE $schema.author IS 'People who write'")
        run("CREATE VIEW $schema.cheap AS SELECT isbn FROM $schema.\"Book\" WHERE price < 10")
        run("CREATE SEQUENCE $schema.ticket_seq START 100")
        run("INSERT INTO $schema.author (name) SELECT 'author ' || g FROM generate_series(1, 1000) g")
        Unit
    }

    @After
    fun tearDown() = runBlocking {
        if (::session.isInitialized) {
            runCatching { run("DROP SCHEMA $schema CASCADE") }
            session.close()
        }
    }

    @Test
    fun browsesSchemasAndObjects() = runBlocking {
        assertTrue(session.serverVersion.startsWith("PostgreSQL"))
        assertTrue(session.listSchemas(null).any { it.name == schema })
        val objects = session.listTables(SchemaRef(null, schema))
        assertEquals(
            listOf(
                "author" to TableType.TABLE,
                // Backing sequence of the identity column.
                "author_id_seq" to TableType.SEQUENCE,
                "Book" to TableType.TABLE,
                "cheap" to TableType.VIEW,
                "ticket_seq" to TableType.SEQUENCE,
            ),
            objects.map { it.name to it.type },
        )
        assertEquals("People who write", objects.first { it.name == "author" }.remarks)
    }

    @Test
    fun describesTable() = runBlocking {
        val book = session.listTables(SchemaRef(null, schema)).first { it.name == "Book" }
        val details = session.describeTable(book)
        assertEquals(listOf("isbn", "edition", "author_id", "price"), details.columns.map { it.name })
        assertEquals(listOf("isbn", "edition"), details.primaryKey?.columns)
        val fk = details.foreignKeys.single()
        assertEquals("author", fk.referencedTable.name)
        assertEquals(listOf("id"), fk.referencedColumns)
        assertEquals(ReferentialAction.CASCADE, fk.onDelete)
        assertTrue(details.indexes.any { it.name == "book_price_idx" && it.columns == listOf("price") })

        val author = session.describeTable(session.listTables(SchemaRef(null, schema)).first { it.name == "author" })
        assertTrue(author.columns.first { it.name == "id" }.autoIncrement)
        assertFalse(author.columns.first { it.name == "name" }.nullable)
    }

    @Test
    fun generatesDdl() = runBlocking {
        val objects = session.listTables(SchemaRef(null, schema)).associateBy { it.name }
        val author = session.ddl(objects.getValue("author"))
        assertTrue(author, author.contains("id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL"))
        assertTrue(author, author.contains("name character varying(100) NOT NULL"))
        assertTrue(author, author.contains("bio text DEFAULT 'n/a'::text"))
        assertTrue(author, author.contains("PRIMARY KEY (id)"))
        assertTrue(author, author.contains("COMMENT ON TABLE $schema.author IS 'People who write';"))

        val book = session.ddl(objects.getValue("Book"))
        assertTrue(book, book.startsWith("CREATE TABLE $schema.\"Book\" ("))
        assertTrue(book, book.contains("CHECK (price >= 0::numeric)"))
        assertTrue(book, book.contains("FOREIGN KEY (author_id) REFERENCES $schema.author(id) ON DELETE CASCADE"))
        assertTrue(book, book.contains("CREATE INDEX book_price_idx ON $schema.\"Book\" USING btree (price DESC);"))
        assertFalse("PK index must not be repeated", book.contains("Book_pkey ON"))

        val view = session.ddl(objects.getValue("cheap"))
        assertTrue(view, view.startsWith("CREATE OR REPLACE VIEW $schema.cheap AS"))
        val seq = session.ddl(objects.getValue("ticket_seq"))
        assertTrue(seq, seq.contains("START WITH 100"))
    }

    @Test
    fun streamsResultsWithCursorAndRestoresAutoCommit() = runBlocking {
        val chunks = session.execute("SELECT id, name FROM $schema.author ORDER BY id", pageSize = 100, maxRows = 250).toList()
        assertEquals(3, chunks.count { it is ResultChunk.Rows })
        val done = chunks.last() as ResultChunk.Completed
        assertEquals(250, done.rowCount)
        assertTrue(done.truncated)
        assertTrue(session.isAutoCommit)
        // A following write must be committed immediately (auto-commit restored).
        assertEquals(ResultChunk.UpdateCount(1), run("UPDATE $schema.author SET name = 'x' WHERE id = 1").first())
    }

    @Test
    fun errorsCarrySqlStateAndPosition() = runBlocking {
        val e = runCatching { run("SELECT nope FROM $schema.author") }.exceptionOrNull() as DbException
        assertEquals("42703", e.sqlState)
        assertEquals(8, e.position)
        assertTrue(e.message!!.contains("nope"))
    }

    @Test
    fun cancelStopsLongQuery() = runBlocking {
        val job = async { runCatching { run("SELECT pg_sleep(30)") } }
        delay(500)
        session.cancel()
        val error = job.await().exceptionOrNull() as? DbException
        assertNotNull(error)
        assertEquals("57014", error!!.sqlState)
    }

    @Test
    fun transactionsRollBack() = runBlocking {
        session.beginTx()
        run("DELETE FROM $schema.author")
        session.rollback()
        val count = run("SELECT count(*) FROM $schema.author").filterIsInstance<ResultChunk.Rows>().single().rows.single().single()
        assertEquals(1000L, count)
    }

    @Test
    fun readOnlyProfileRejectsWritesInAutoCommit() = runBlocking {
        val ro = PostgresDriver().connect(profile(readOnly = true), secrets)
        try {
            val e = runCatching { ro.execute("DELETE FROM $schema.author").toList() }.exceptionOrNull() as DbException
            assertEquals("25006", e.sqlState) // read_only_sql_transaction
        } finally {
            ro.close()
        }
    }

    @Test
    fun unreachablePortFailsCleanly() = runBlocking {
        val e = runCatching { PostgresDriver().connect(profile().copy(host = "127.0.0.1", port = 1), secrets) }.exceptionOrNull()
        assertTrue("expected DbException, got $e", e is DbException)
    }
}
